version: "3.3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my_app_network
  node-app:
    build: .
    env_file:
      - ./.env
    depends_on:
      - redis-app
      - mongo
    networks:
      - my_app_network
  mongo:
    image: mongo:4.4.14
    volumes:
      - mongo_volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - my_app_network
  redis-app:
    image: redis
    networks:
      - my_app_network
volumes:
  mongo_volume: 
networks:
  my_app_network:
    driver: bridge

    
