version: "3.3"
services:
  node-app:
    build: .
    ports:
      - "3000:4000"
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:4.4.14
    volumes:
      - mongo_volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=password
  redis:
    image: redis:5.0.14
volumes:
  mongo_volume: 

    