version: "3.3"
services:
  node-app:
    build: .
    ports:
      - "3000:4000"
    env_file:
      - ./.env
    depends_on:
      - redis-app
      - mongo
    networks:
      - my_app_network
  mongo:
    image: mongo:4.4.14
    volumes:
      - mongo_volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - my_app_network
  redis-app:
    image: redis
    networks:
      - my_app_network
volumes:
  mongo_volume: 
networks:
  my_app_network:
    driver: bridge

    